service: hotdog

provider:
  name: aws
  runtime: nodejs6.10

  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "rekognition:DetectLabels"
      Resource: "*"
    - Effect: "Allow"
      Action:
        - "s3:*"
      Resource:
        - "arn:aws:s3:::secrethotdogbucket/*"

functions:
  home:
    handler: handler.home
    events:
      - http:
          path: /
          method: get

  patreon:
    handler: handler.patreon
    events:
      - http:
          path: /patreon
          method: post
    environment:
      PATREON_SECRET: ${opt:patreon}

  request_upload_url:
    handler: handler.requestUploadURL
    events:
      - http:
          path: requestUploadURL
          method: post
          cors: true

  detect_hotdog:
    handler: handler.detectHotDog
    events:
      - http:
          path: detect
          method: post
          cors: true


# you can add CloudFormation resource templates here
resources:
  Resources:
    ImgBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: secrethotdogbucket
        AccessControl: PublicRead
        CorsConfiguration:
          CorsRules:
          - AllowedMethods:
            - GET
            - PUT
            - POST
            - HEAD
            AllowedOrigins:
            - "*"
            AllowedHeaders:
            - "*"